CREATE TABLE IF NOT EXISTS customers(id BIGSERIAL PRIMARY KEY, name VARCHAR(180) NOT NULL, email VARCHAR(220), active BOOLEAN NOT NULL);
CREATE TABLE IF NOT EXISTS orders(id BIGSERIAL PRIMARY KEY, customer_id BIGINT NOT NULL, amount NUMERIC(19,4) NOT NULL, status VARCHAR(24) NOT NULL);
CREATE TABLE IF NOT EXISTS migration_state(
 id INT PRIMARY KEY CHECK(id=1), stage TEXT NOT NULL DEFAULT 'IDLE', status TEXT NOT NULL DEFAULT 'IDLE',
 primary_db TEXT NOT NULL DEFAULT 'SQL_SERVER', current_table TEXT NOT NULL DEFAULT 'CUSTOMERS',
 last_id BIGINT NOT NULL DEFAULT 0, customer_bound BIGINT NOT NULL DEFAULT 0, order_bound BIGINT NOT NULL DEFAULT 0,
 version BIGINT NOT NULL DEFAULT 0, copied BIGINT NOT NULL DEFAULT 0, expected BIGINT NOT NULL DEFAULT 0,
 batches BIGINT NOT NULL DEFAULT 0, applied BIGINT NOT NULL DEFAULT 0, traffic BOOLEAN NOT NULL DEFAULT FALSE,
 crash_requested BOOLEAN NOT NULL DEFAULT FALSE, traffic_step BIGINT NOT NULL DEFAULT 0, validation TEXT NOT NULL DEFAULT 'Not checked', error TEXT NOT NULL DEFAULT '',
 checkpoint TIMESTAMPTZ, rows_per_second DOUBLE PRECISION NOT NULL DEFAULT 0);
INSERT INTO migration_state(id) VALUES(1) ON CONFLICT DO NOTHING;
CREATE TABLE IF NOT EXISTS migration_log(id BIGSERIAL PRIMARY KEY, at TIMESTAMPTZ NOT NULL DEFAULT now(), message TEXT NOT NULL);

ALTER TABLE migration_state ADD COLUMN IF NOT EXISTS cdc_paused BOOLEAN NOT NULL DEFAULT FALSE;
CREATE TABLE IF NOT EXISTS replay_receipt(table_name TEXT NOT NULL, record_id BIGINT NOT NULL, version BIGINT NOT NULL, PRIMARY KEY(table_name,record_id));
CREATE TABLE IF NOT EXISTS traffic_metrics(
 id INT PRIMARY KEY CHECK(id=1), inserts BIGINT NOT NULL DEFAULT 0, updates BIGINT NOT NULL DEFAULT 0,
 deletes BIGINT NOT NULL DEFAULT 0, reads BIGINT NOT NULL DEFAULT 0, errors BIGINT NOT NULL DEFAULT 0,
 consecutive_errors INT NOT NULL DEFAULT 0, sql_server_ops BIGINT NOT NULL DEFAULT 0, postgres_ops BIGINT NOT NULL DEFAULT 0,
 window_started TIMESTAMPTZ NOT NULL DEFAULT now(), window_ops BIGINT NOT NULL DEFAULT 0, ops_per_second DOUBLE PRECISION NOT NULL DEFAULT 0);
INSERT INTO traffic_metrics(id) VALUES(1) ON CONFLICT DO NOTHING;
